version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=chatrooms

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=chatrooms
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
